Health check reconciler
linode/provider-ceph pull request #11
Opened 2023-05-18 14:57 UTC by nolancon

### Description of your changes
Add reconcile loop to perform health check on s3 backends and update corresponding `ProviderConfig`.
The health check creates a `Bucket` initially. Then performs a `PutObject` and `GetObject` at the specified interval (default 30s) as these operations are less taxing. 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested
Kuttl assertions are updated with health status in CRs

[contribution process]: https://git.io/fj2m9

2023-05-22 09:10 UTC, mhmxs requested changes

2023-05-22 09:44 UTC, nolancon commented on apis/v1alpha1/providerconfig_types.go
> +	Health string `json:"health,omitempty"`
I think the most kubernetes-ish way to do this is probably to declare a `type` and `const` within the api, like in this example https://github.com/kubernetes/api/blob/2f9553831ec24dc60e3e1c3a374fb63ca091688f/core/v1/types.go#L6561 WDYT?

2023-05-22 09:50 UTC, nolancon commented on internal/controller/providerconfig/healthcheck_controller.go
> +		case <-ticker.C:
Yes, I was going off the precedent of the old operator for a retry period :sweat_smile: https://github.com/storageos/operator/blob/c44a8254c21bc7bc3d0405142358dc4546429b37/controllers/storageoscluster/operator.go#L117
Do you think 5 seconds is too long before attempting to retry? We could set it via CR with a default, but I'm not sure it's necessary :shrug:

2023-05-22 15:18 UTC, nolancon commented on internal/controller/providerconfig/healthcheck_controller.go
> +		case <-ticker.C:
I see now - Addressed in https://github.com/linode/provider-ceph/pull/11/commits/5fa3570e2f35eb0587c7c20159d085b11ffe0d7c

2023-05-30 08:59 UTC, mhmxs approved these changes

2023-05-30 09:04 UTC, mhmxs requested changes
Open questions need to be fixed

2023-06-01 11:21 UTC, merged